import type { Metadata } from "next";
import Link from "next/link";
import ErrorButton from "@/components/ErrorButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  return (
    <html lang={locale}>
      <body>
        <nav>
          <div><Link href="/en">home page</Link></div>
          <div><Link href="/en/login">login page</Link></div>
        </nav>
        <h1>layout.tsx (root)</h1>
        <ErrorButton />
        {children}
      </body>
    </html>
  );
}
